name: Trigger auto deployment for container-app-5dhbbwnns5y4y

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-5dhbbwnns5y4y-AutoDeployTrigger-dec9d948-493e-4874-9616-68c723c6a1a2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP5DHBBWNNS5Y4Y_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP5DHBBWNNS5Y4Y_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP5DHBBWNNS5Y4Y_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP5DHBBWNNS5Y4Y_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP5DHBBWNNS5Y4Y_REGISTRY_PASSWORD }}
          containerAppName: container-app-5dhbbwnns5y4y
          resourceGroup: appspaceragpython8061
          imageToBuild: default/container-app-5dhbbwnns5y4y:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


